# Generated by Django 4.1.7 on 2023-03-23 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2560)),
                ('price', models.IntegerField(verbose_name=[django.core.validators.MinValueValidator(0)])),
                ('toppings', models.ManyToManyField(to='relationship_playground.topping')),
            ],
        ),
    ]
